databases:
  - name: learning-db
    databaseName: learning_platform
    plan: free

services:
  # 1. Infrastructure: Redis for Messaging (as a Private Service)
  - type: pserv
    name: messaging-redis
    env: redis
    plan: free

  # 2. Microservice: Discovery Service (Eureka)
  - type: pserv
    name: discovery-service
    env: java
    rootDir: ./discovery-service
    buildCommand: mvn clean install
    startCommand: java -jar target/discovery-service-*.jar
    healthCheckPath: /
    envVars:
      - key: SERVER_PORT
        value: 8761

  # 3. Microservice: User Service
  - type: pserv
    name: user-service
    env: java
    rootDir: ./user-service
    buildCommand: mvn clean install
    startCommand: java -jar target/user-service-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: learning-db
          property: connectionString
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: pserv
          name: messaging-redis
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka

  # 4. Microservice: Course Service
  - type: pserv
    name: course-service
    env: java
    rootDir: ./course-service
    buildCommand: mvn clean install
    startCommand: java -jar target/course-service-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: learning-db
          property: connectionString
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: pserv
          name: messaging-redis
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka

  # 5. Microservice: Enrollment Service
  - type: pserv
    name: enrollment-service
    env: java
    rootDir: ./enrollment-service
    buildCommand: mvn clean install
    startCommand: java -jar target/enrollment-service-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: learning-db
          property: connectionString
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: pserv
          name: messaging-redis
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka

  # 6. Microservice: Notification Service
  - type: pserv
    name: notification-service
    env: java
    rootDir: ./notification-service
    buildCommand: mvn clean install
    startCommand: java -jar target/notification-service-*.jar
    envVars:
      - key: SPRING_DATA_REDIS_URL
        fromService:
          type: pserv
          name: messaging-redis
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka

  # 7. Microservice: API Gateway (The only public service)
  - type: web
    name: api-gateway
    env: java
    rootDir: ./api-gateway
    buildCommand: mvn clean install
    startCommand: java -jar target/api-gateway-*.jar
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://discovery-service:8761/eureka